version: 1.1.{build}
image: Visual Studio 2019


environment:
  matrix:
    - PlatformToolset: v142

platform:
    - Any CPU

configuration:
    - Release
    - Debug



build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild WpfClipboardMonitor.sln /m /verbosity:minimal /t:WpfClipboardMonitorFramework40;WpfClipboardMonitorCore30;ImageCatcherEventFramework40;ImageCatcherEventCore30;ImageCatcherMemberFramework40;ImageCatcherMemberCore30;ImageCatcherMvvmFramework40;ImageCatcherMvvmCore30;ImageCatcherOverrideFramework40;ImageCatcherOverrideCore30 /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

# after_build:
    # - cd "%APPVEYOR_BUILD_FOLDER%"
    # - ps: >-
        # Push-AppveyorArtifact "WpfClipboardMonitor\bin\$env:CONFIGURATION\WpfClipboardMonitor.dll" -FileName WpfClipboardMonitor.dll

        # if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v142") {
            # $ZipFileName = "WpfClipboardMonitor_$($env:APPVEYOR_REPO_TAG_NAME).zip"
            # 7z a $ZipFileName WpfClipboardMonitor\bin\$env:CONFIGURATION\WpfClipboardMonitor.dll
        # }

# artifacts:
  # - path: WpfClipboardMonitor_*.zip
    # name: releases

# deploy:
    # provider: GitHub
    # auth_token:
        # secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    # artifact: releases
    # draft: false
    # prerelease: false
    # force_update: true
    # on:
        # appveyor_repo_tag: true
        # PlatformToolset: v142
        # configuration: Release
