version: 1.2.0.{build}
image: Visual Studio 2022


platform:
    - Any CPU

configuration:
    - Release
    - Debug

install:
    - copy /y "%APPVEYOR_BUILD_FOLDER%"\DummySignKey.snk "%APPVEYOR_BUILD_FOLDER%"\Src\WpfClipboardMonitor70\Bassman.snk
    - copy /y "%APPVEYOR_BUILD_FOLDER%"\DummySignKey.snk "%APPVEYOR_BUILD_FOLDER%"\Src\WpfClipboardMonitor60\Bassman.snk
    - copy /y "%APPVEYOR_BUILD_FOLDER%"\DummySignKey.snk "%APPVEYOR_BUILD_FOLDER%"\Src\WpfClipboardMonitor50\Bassman.snk
    - copy /y "%APPVEYOR_BUILD_FOLDER%"\DummySignKey.snk "%APPVEYOR_BUILD_FOLDER%"\Src\WpfClipboardMonitorCore31\Bassman.snk
    - copy /y "%APPVEYOR_BUILD_FOLDER%"\DummySignKey.snk "%APPVEYOR_BUILD_FOLDER%"\Src\WpfClipboardMonitorFramework40\Bassman.snk
    - copy /y "%APPVEYOR_BUILD_FOLDER%"\DummySignKey.snk "%APPVEYOR_BUILD_FOLDER%"\Src\WpfClipboardMonitorFramework45\Bassman.snk
    - copy /y "%APPVEYOR_BUILD_FOLDER%"\DummySignKey.snk "%APPVEYOR_BUILD_FOLDER%"\Src\WpfClipboardMonitorFramework48\Bassman.snk

    - ps: >-
        Start-FileDownload 'https://github.com/EWSoftware/SHFB/releases/download/v2022.12.30.0/SHFBInstaller_2022.12.30.0.zip'

        7z x -y SHFBInstaller_2022.12.30.0.zip | Out-Null

        Write-Host "Installing MSI..."

        cmd /c start /wait msiexec /i InstallResources\SandcastleHelpFileBuilder.msi /quiet

        Write-Host "Installing VSIX..."

        . "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe" /q /a InstallResources\SHFBVisualStudioPackage_VS2022AndLater.vsix

        Write-Host "Sandcastle installed" -ForegroundColor Green

    - set SHFBROOT=C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\

    - nuget restore WpfClipboardMonitor.sln

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    ####- msbuild WpfClipboardMonitor.sln /m /verbosity:minimal /t:restore /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild WpfClipboardMonitor.sln /m /verbosity:minimal /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    ####- msbuild WpfClipboardMonitorPreview.sln /m /verbosity:minimal /t:restore /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - cd "%APPVEYOR_BUILD_FOLDER%"\Nuget
    - if "%configuration%"=="Release" nuget pack WpfClipboardMonitor.nuspec -properties Configuration=Release

#after_build:
#     - cd "%APPVEYOR_BUILD_FOLDER%"
#     - ps: >-
#        Push-AppveyorArtifact "Nuget\WpfClipboardMonitor.1.2.0.nupkg" -FileName WpfClipboardMonitor.1.2.0.nupkg

        # if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release") {
            # $ZipFileName = "WpfClipboardMonitor_$($env:APPVEYOR_REPO_TAG_NAME).zip"
            # 7z a $ZipFileName WpfClipboardMonitor\bin\$env:CONFIGURATION\WpfClipboardMonitor.dll
        # }

# artifacts:
  # - path: WpfClipboardMonitor_*.zip
    # name: releases

# deploy:
    # provider: GitHub
    # auth_token:
        # secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    # artifact: releases
    # draft: false
    # prerelease: false
    # force_update: true
    # on:
        # appveyor_repo_tag: true
        # configuration: Release
