name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    environment: sign
    env:
        SHFBROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Github]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
    
    - name: Add SignKeys
      uses: Bassman2/SignKey@v1
      with:
        file: Bassman.snk
        key: ${{ secrets.SIGNKEY }}
        
    - name: Install SHFB
      uses: Bassman2/setup-SHFB@v1

    - name: Nuget restore solution
      run: nuget restore WpfClipboardMonitor.sln

    - name: MSBuild of solution
      run: msbuild WpfClipboardMonitor.sln /p:configuration="${{ matrix.build_configuration }}" /m /verbosity:minimal      
        
    - name: Nuget pack nuspec
      if: matrix.build_configuration == 'Release'
      working-directory: .\Nuget\
      run: nuget pack WpfClipboardMonitor.nuspec -properties Configuration="${{ matrix.build_configuration }}"