name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Github]
        
    steps:
    
    - name: test
      run: |
           echo SIGNKEYFILE1: %SIGNKEYFILE% 
           echo SIGNKEYFILE2: ${{ secrets.SIGNKEYFILE }} 
      env: 
           SIGNKEYFILE: ${{ secrets.SIGNKEYFILE }} 
      shell: cmd
      
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Install SHFB
      uses: Bassman2/setup-SHFB@v2
      with:
        version: 2022.12.30.0
        
    - name: Copy dummy key for signing
      run: |
           Copy-Item  DummySignKey.snk -Destination Src\WpfClipboardMonitor70\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\WpfClipboardMonitor60\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\WpfClipboardMonitor50\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\WpfClipboardMonitorCore31\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\WpfClipboardMonitorFramework40\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\WpfClipboardMonitorFramework45\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\WpfClipboardMonitorFramework48\Bassman.snk

    - name: Nuget restore solution
      run: nuget restore WpfClipboardMonitor.sln

    - name: MSBuild of solution
      run: msbuild WpfClipboardMonitor.sln /p:configuration="${{ matrix.build_configuration }}" /m /verbosity:minimal

    - name: Nuget pack nuspec
      if: matrix.build_configuration == 'Release'
      working-directory: .\Nuget\
      run: nuget pack WpfClipboardMonitor.nuspec -properties Configuration="${{ matrix.build_configuration }}"