name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [Any CPU]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Setup to add MSBuild.exe to path
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: restore
      working-directory: 
      run: msbuild WpfClipboardMonitor.sln /m /verbosity:minimal /t:restore /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: MSBuild of solution
      working-directory: 
      run: msbuild WpfClipboardMonitor.sln /m /verbosity:minimal /t:WpfClipboardMonitorFramework40;WpfClipboardMonitorCore30 /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
          name: WpfClipboardMonitorFramework40
          path: WpfClipboardMonitorFramework40\bin\${{ matrix.build_configuration }}\WpfClipboardMonitor.dll

