name: DotNet Continuous Integration

on: 
  push:
    branches: [ "master", ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    environment: sign
    env:
      Solution: WpfClipboardMonitor.sln
      SHFBROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Release, Debug]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Add SignKeys
      uses: Bassman2/SignKey@v1
      with:
        file: Bassman.snk
        key: ${{ secrets.SIGNKEY }}
        
    - name: Install SHFB
      uses: Bassman2/setup-SHFB@v1

    - name: Dotnet restore dependencies
      run: dotnet restore $env:Solution

    - name: Dotnet build
      run: dotnet build $env:Solution --no-restore
      
   